language: java
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]$/"
    - master
notifications:
  email:
    recipients:
      - bryan.jimenez@gmail.com
  slack:
    secure:
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=crowded1984
    -Dsonar.login=$SONAR
deploy:
  provider: heroku
  api_key: "$HEROKU"
  skip_cleanup: true
  on:
    branch: master
